Fiap.Web.AspNet2/Controllers/RepresentanteController.cs
//using Fiap.Web.AspNet2.Models;
using AutoMapper;
using Fiap.Web.AspNet2.Models;
using Fiap.Web.AspNet2.Repository.Interface;
using Fiap.Web.AspNet2.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace Fiap.Web.AspNet2.Controllers
{
    public class RepresentanteController : Controller
    {
        private readonly IRepresentanteRepository representanteRepository;
        private readonly IMapper mapper;

        public RepresentanteController( IRepresentanteRepository _representanteRepository, IMapper _mapper )
        {
            representanteRepository = _representanteRepository;
            mapper = _mapper;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var representantes = 
                mapper.Map<IList<RepresentanteViewModel>>(representanteRepository.FindAll());

            return View(representantes);
        }

        [HttpGet]
        public IActionResult Novo()
        {
            return View(new RepresentanteViewModel());
        }

        [HttpPost]
        public IActionResult Novo(RepresentanteViewModel representanteVM)
        {
            var representanteModel = mapper.Map<RepresentanteModel>(representanteVM);

            representanteRepository.Insert(representanteModel);

            TempData["mensagemSucesso"] = $"Representante {representanteVM.NomeRepresentante} cadastrado com sucesso";
            return RedirectToAction("Index");
        }


        // Abrindo a tela de alteração
        [HttpGet]
        public IActionResult Alterar(int id)
        {
            var representanteModel = representanteRepository.FindByIdWithClientes(id);
            var representanteVM = mapper.Map<RepresentanteViewModel>(representanteModel);

            return View(representanteVM);
        }

        //Capturando os dados, gravando no banco e exibindo a mensagem de sucesso.
        [HttpPost]
        public IActionResult Alterar(RepresentanteViewModel representanteVM)
        {
            var representanteModel = mapper.Map<RepresentanteModel>(representanteVM);

            representanteRepository.Update(representanteModel);

            TempData["mensagemSucesso"] = $"Representante {representanteVM.NomeRepresentante} alterado com sucesso";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Excluir(int id)
        {
            representanteRepository.Delete(id);
            TempData["mensagemSucesso"] = $"Representante removido com sucesso";
            return RedirectToAction("Index");
        }

    }
}

Fiap.Web.AspNet2/Views/Representante/Alterar.cshtml
@model Fiap.Web.AspNet2.ViewModel.RepresentanteViewModel

@{

}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="well">
                <h2>Representante - Alterar</h2>

                <form asp-controller="Representante" asp-action="Alterar" method="post">
                    <input asp-for="RepresentanteId" />

                    <div class="form-group">
                        <label class="control-label" asp-for="NomeRepresentante"></label>
                        <input class="form-control col-5" asp-for="NomeRepresentante" />
                    </div>
                    

                    @if (Model.Clientes.Count() > 0) {
                    <h2>Cliente:</h2>
                        @foreach(var item in Model.Clientes)
                        {
                            @item.Nome <br />
                        }
                    }

                    <a href="#" class="btn btn-default btn-lg">Cancelar</a>
                    <button type="submit" class="btn btn-primary btn-lg">Gravar</button>
                </form>
            </div>
        </div>
    </div>
</div>

Fiap.Web.AspNet2/Views/Representante/Index.cshtml
@model IEnumerable<Fiap.Web.AspNet2.ViewModel.RepresentanteViewModel>

<div class="container">
    <div class="row">
        <div class="col-md-12">


            <h1>Representantes</h1>
            <p class="toolbar">

                <a class="create btn btn-default" asp-controller="Representante" asp-action="Novo">Novo Representante</a>
            </p>

            @{
                String mensagemSucesso = (String)TempData["mensagemSucesso"];
                if (!String.IsNullOrEmpty(mensagemSucesso))
                {
                    <div class="alert alert-warning" role="alert">
                        <h4>@mensagemSucesso</h4>
                    </div>
                }
            }




            @if (Model.Count() > 0)
            {
                <table class="table table-striped" border="1" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th data-field="id">Id</th>
                            <th data-field="name">Nome</th>
                            <th class="actions" width="220">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>#@item.RepresentanteId</td>
                            <td>@item.NomeRepresentante</td>
                            <td>
                                <a class="btn btn-warning btn-sm"
                                   asp-controller="Representante"
                                   asp-action="Alterar"
                                   asp-route-id="@item.RepresentanteId">Editar</a>
                                <a class="btn btn-danger btn-sm"
                                   asp-controller="Representante"
                                   asp-action="Excluir"
                                   asp-route-id="@item.RepresentanteId">Excluir</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-warning" role="alert">
                    <h4>Não existem representantes cadastrados até o momento.</h4>
                </div>
            }


        </div>
    </div>
</div>

Fiap.Web.AspNet2/Views/Representante/Novo.cshtml
@model Fiap.Web.AspNet2.ViewModel.RepresentanteViewModel

@{

}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="well">
                <h2>Representante - Novo</h2>

                <form asp-controller="Representante" asp-action="Novo" method="post">
                    <input type="hidden" asp-for="RepresentanteId" />

                    <div class="form-group">
                        <label class="control-label" asp-for="NomeRepresentante"></label>
                        <input class="form-control col-5" asp-for="NomeRepresentante" />
                    </div>

                    <a href="#" class="btn btn-default btn-lg">Cancelar</a>
                    <button type="submit" class="btn btn-primary btn-lg">Gravar</button>
                </form>
            </div>
        </div>
    </div>
</div>