Fiap.Web.AspNet2/Controllers/ClienteController.cs
using Fiap.Web.AspNet2.Controllers.Filters;
using Fiap.Web.AspNet2.Models;
using Fiap.Web.AspNet2.Repository.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace Fiap.Web.AspNet2.Controllers
{
    
    public class ClienteController : Controller
    {

        private readonly IClienteRepository clienteRepository;
        private readonly IRepresentanteRepository representanteRepository;

        public ClienteController(IClienteRepository _clienteRepository, IRepresentanteRepository _representanteRepository)
        {
            clienteRepository = _clienteRepository;
            representanteRepository = _representanteRepository;
        }


        [HttpGet]
        public IActionResult Index()
        {
            //IList<ClienteModel> clientes = clienteRepository.FindAll();
            IList<ClienteModel> clientes = clienteRepository.FindByEmailAndRepresentante("", 0);

            return View(clientes);
        }

        [HttpGet]
        public IActionResult Novo()
        {
            IList<RepresentanteModel> representantes = representanteRepository.FindAll();
            ViewBag.Representantes = representantes;

            return View(new ClienteModel());
        }

        [HttpPost]
        public IActionResult Novo(ClienteModel clienteModel)
        {
            clienteRepository.Insert(clienteModel);

            TempData["mensagemSucesso"] = $"Cliente {clienteModel.Nome} cadastrado com sucesso";
            return RedirectToAction("Index");
        }


        // Abrindo a tela de alteração
        [HttpGet]
        public IActionResult Alterar(int id)
        {
            ClienteModel clienteModel = clienteRepository.FindById(id);

            IList<RepresentanteModel> representantes = representanteRepository.FindAll();
            ViewBag.Representantes = new SelectList(representantes, "RepresentanteId", "NomeRepresentante");

            return View(clienteModel);
        }

        //Capturando os dados, gravando no banco e exibindo a mensagem de sucesso.
        [HttpPost]
        [FiapFilter]
        public IActionResult Alterar(ClienteModel clienteModel)
        {
            clienteRepository.Update(clienteModel);

            TempData["mensagemSucesso"] = $"Cliente {clienteModel.Nome} alterado com sucesso";
            return RedirectToAction("Index");
        }

        [HttpGet]
        [FiapFilter]
        public IActionResult Detalhe(int id)
        {
            var clienteModel = clienteRepository.FindById(id);
            return View(clienteModel);
        }


        [HttpGet]
        public IActionResult Excluir(int id)
        {
            clienteRepository.Delete(id);
            TempData["mensagemSucesso"] = $"Cliente removido com sucesso";
            return RedirectToAction("Index");
        }


    }

}

Fiap.Web.AspNet2/Controllers/LoginController.cs
using Fiap.Web.AspNet2.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Web.AspNet2.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel loginViewModel)
        {

            if ( loginViewModel.Usuario.Equals("admin") && loginViewModel.Senha.Equals("1234")) 
            {
                loginViewModel.NomeUsuario = "Usuário Admin do Site";
                HttpContext.Session.SetString("usuarioLogado", loginViewModel.NomeUsuario);

                TempData["mensagemSucesso"] = $"Login efetuado com sucesso";
            } else
            {
                HttpContext.Session.Clear();
                TempData["mensagemSucesso"] = $"Usuário ou senha inválida";
            }

            return RedirectToAction("Index");
        }

    }
}

Fiap.Web.AspNet2/Controllers/LojaController.cs
using Fiap.Web.AspNet2.Models;
using Fiap.Web.AspNet2.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Fiap.Web.AspNet2.Controllers
{
    public class LojaController : Controller
    {

        private readonly ILojaRepository lojaRepository;

        public LojaController(ILojaRepository _ilojaRepository)
        {
            lojaRepository = _ilojaRepository;
        }

        public ActionResult Index()
        {
            IList<LojaModel> lojas = lojaRepository.FindAll();

            return View(lojas);
        }

        public ActionResult Details(int id)
        {
            return View( lojaRepository.FindById(id) );
        }

        public ActionResult Create()
        {
            return View( new LojaModel() );
        }

        [HttpPost]
        public ActionResult Create(LojaModel lojaModel)
        {
            lojaRepository.Insert(lojaModel);

            TempData["mensagemSucesso"] = "Loja cadastrada com sucesso";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            return View(lojaRepository.FindById(id) );
        }

        [HttpPost]
        public ActionResult Edit(LojaModel lojaModel)
        {
            lojaRepository.Update(lojaModel);

            TempData["mensagemSucesso"] = "Loja alterada com sucesso";
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            lojaRepository.Delete(id);
            TempData["mensagemSucesso"] = "Loja removida com sucesso";
            return RedirectToAction("Index");
        }

    }
}

Fiap.Web.AspNet2/Controllers/ProdutoController.cs
using Fiap.Web.AspNet2.Models;
using Fiap.Web.AspNet2.Repository.Interface;
using Fiap.Web.AspNet2.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace Fiap.Web.AspNet2.Controllers
{
    public class ProdutoController : Controller
    {

        private readonly ILojaRepository lojaRepository;
        private readonly IProdutoRepository produtoRepository;

        public ProdutoController(ILojaRepository _lojaRepository, IProdutoRepository _produtoRepository)
        {
            lojaRepository = _lojaRepository;
            produtoRepository = _produtoRepository;
        }



        public ActionResult Index()
        {
            return View( produtoRepository.FindAll() );
        }

        public ActionResult Details(int id)
        {
            return View( produtoRepository.FindById(id) );
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Lojas = lojaRepository.FindAll();
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProdutoLojaViewModel produtoVM)
        {
            ProdutoModel produtoModel = produtoVM.Produto;
            produtoModel.ProdutoLojas = new List<ProdutoLojaModel>();

            foreach (var loja in produtoVM.LojaId)
            {
                var produtoLojaModel = new ProdutoLojaModel()
                {
                    LojaId = loja,
                    Produto = produtoModel
                };

                produtoModel.ProdutoLojas.Add(produtoLojaModel);
            }


            produtoRepository.Insert(produtoModel);

            TempData["mensagemSucesso"] = "Produto cadastrado com sucesso";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            // Listando todas as lojas
            var lojas = lojaRepository.FindAll();
            ViewBag.Lojas = new SelectList(lojas, "LojaId", "NomeLoja");

            
            // Consultando o Produto
            var produtoModel = produtoRepository.FindById(id);
            var produtoLojaVM = new ProdutoLojaViewModel();
            produtoLojaVM.Produto = produtoModel;
            produtoLojaVM.LojaId = produtoModel.ProdutoLojas.Select( l => l.LojaId).ToList();

            return View(produtoLojaVM);
        }

        [HttpPost]
        public ActionResult Edit(ProdutoLojaViewModel produtoVM)
        {
            ProdutoModel produtoModel = produtoVM.Produto;
            produtoModel.ProdutoLojas = new List<ProdutoLojaModel>();

            foreach (var loja in produtoVM.LojaId)
            {
                var produtoLojaModel = new ProdutoLojaModel()
                {
                    LojaId = loja,
                    Produto = produtoModel
                };

                produtoModel.ProdutoLojas.Add(produtoLojaModel);
            }


            produtoRepository.Update(produtoModel);

            TempData["mensagemSucesso"] = "Produto alterado com sucesso";
            return RedirectToAction("Index");
        }

        /*
        // GET: ProdutoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProdutoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        */
        
    }
}

Fiap.Web.AspNet2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fiap.Web.AspNet2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js" crossorigin="anonymous" ></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fiap.Web.AspNet2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Representante" asp-action="Index">Representante</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loja" asp-action="Index">Loja</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Fiap.Web.AspNet2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>